
<?php 
$name=$_REQUEST['name']);
$email=$_REQUEST['email'];
$user_name=$_REQUEST['user_name'];
$password=$_REQUEST['password'];
$conf_password=$_REQUEST['conf_password'];
$birthday=$_REQUEST['birthday'];
$gender=$_REQUEST['gender'];
$status=$_REQUEST['status'];
$address=$_REQUEST['address'];
$city=$_REQUEST['city'];
$code=$_REQUEST['code'];
$home_phone=$_REQUEST['home_phone'];
$mob_phone=$_REQUEST['mob_phone'];
$c_number=$_REQUEST['c_number'];
$c_expiry=$_REQUEST['c_expiry'];
$salary=$_REQUEST['salary'];
$url=$_REQUEST['url'];
$gpa=$_REQUEST['gpa'];	
?>